### ISSUE TITLE
Homography example

### ISSUE THREAD

**Issue by SWAT-Brasil** [lessthanoptimal/GeoRegression#15]
Would you have an Homography example so I can understand how to use it?

**Comment by JairoRotava** [comment]
I guess this is a good example to remove perspective distortion:
https://github.com/lessthanoptimal/BoofCV/blob/SNAPSHOT/examples/src/main/java/boofcv/examples/geometry/ExampleRemovePerspectiveDistortion.java

It is not clear to me what is the main difference between boofcv and georegression. Whats is the main role to georegression? I think there is no such separation in Opencv, so I'm having so difficult to understand.

**Comment by lessthanoptimal** [comment]
@JairoRotava 
GeoRegression did start off as a module in BoofCV a long time ago. It got broken off into it's own library because other projects needed to use it and were not computer vision projects. OpenCV uses a combination of wrapping 3rd party libraries and rolling their own. It's normal to have SE3 and SE2 be it's own library along with many of the other geometric primitives. Having Perspective geometry in GeoRegression is unusual but I think makes more sense in the long term.

Having said all of that, linking to external use cases is a good idea!

@SWAT-Brasil Does all of this answer your question?

**Comment by SWAT-Brasil** [comment]
@lessthanoptimal Thanks.
I suggest to add some reference to GeoRegression on BoofCV webpage. I just found this digging the Boofcv source code.
